-- 1. Scores Table (For Leaderboards & Mission Results)
CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    score BIGINT NOT NULL,
    difficulty TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_scores_leaderboard ON scores (difficulty, score DESC);

CREATE INDEX IF NOT EXISTS idx_scores_username ON scores (username);

-- 2. User Progress Table (Total XP, Campaign Level)
CREATE TABLE IF NOT EXISTS user_progress (
    username TEXT PRIMARY KEY,
    highest_mission_id BIGINT DEFAULT 1,
    xp BIGINT DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);